PREFIX ECO: <http://purl.obolibrary.org/obo/ECO_>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?eco ?go ?def WHERE {
  ?c oboInOwl:id ?eco ;
     ECO:9000002 ?go .
  OPTIONAL {
    ?ax a owl:Axiom ;
        owl:annotatedSource ?c ;
        owl:annotatedProperty ECO:9000002 ;
        owl:annotatedTarget ?go ;
        rdfs:comment ?def
  }
}
ORDER BY ?go ?def
